---
# this specifies which servers to run this on
- hosts: all
  gather_facts: false
# means to become sudo
  become: true
  become_user: root
  become_method: sudo
  vars:
    created_username: ns-quinlan

  tasks:
    - name: Update apt
      apt:
        update_cache: yes
        upgrade: 'yes'  
    - name: Update apt and install required system packages
      apt:
        pkg:
          - curl
          - vim
          - git
          - rsync
          - nginx
          - nginx-extras
          - python3-pip
          - python3-dev
          - build-essential
          - libssl-dev
          - libffi-dev
          - python3-setuptools
          - zlib1g-dev
          - libncurses5-dev
          - libgdbm-dev
          - libnss3-dev
          - libreadline-dev
          - python3-venv
          - wget
          - unzip
        allow_unauthenticated: true
        state: latest
        update_cache: true
    - name: Configuring Ubuntu user
      expect:
        command: sudo passwd ubuntu
        responses:
          "New password:": "ubuntu"
          "Retype new password:": "ubuntu"
        timeout: 200
    - name: Cloning GitHub Repository
      git:
       repo: ChangeMe!
       dest: /home/ubuntu/temp-repo/
       version: OpenCTI
    - name: Update the website files
      command: rsync -av --delete --exclude="/project-emu-develop/data" /home/ubuntu/temp-repo/ /home/ubuntu/OpenCTI/
    - name: Clean up
      file:
        path: /home/ubuntu/temp-repo/
        state: absent
    - name: Configuring OpenCTI Directory
      shell: |
        sudo unzip -o /home/ubuntu/GIS-SecEng-Intern/project-emu-develop.zip -d /home/ubuntu/GIS-SecEng-Intern/
        sudo chmod -R u+rwx /home/ubuntu/GIS-SecEng-Intern/project-emu-develop/
        sudo chown -R ubuntu:ubuntu /home/ubuntu/GIS-SecEng-Intern/project-emu-develop/
        mv /home/ubuntu/GIS-SecEng-Intern/Ansible/files/.env /home/ubuntu/GIS-SecEng-Intern/project-emu-develop/.env
        cd /home/ubuntu/GIS-SecEng-Intern/project-emu-develop/
        make
        cd
    - name: Python Virtual Environment
      shell: |
        sudo python3 -m venv /home/ubuntu/GIS-SecEng-Intern/project-emu-develop/venv
        sudo chmod -R u+rwx /home/ubuntu/GIS-SecEng-Intern/project-emu-develop/venv
        sudo chown -R ubuntu:ubuntu /home/ubuntu/GIS-SecEng-Intern/project-emu-develop/venv
        sudo /home/ubuntu/GIS-SecEng-Intern/project-emu-develop/venv/bin/pip3 install --upgrade pip
        sudo /home/ubuntu/GIS-SecEng-Intern/project-emu-develop/venv/bin/pip3 install wheel gunicorn Flask
        sudo /home/ubuntu/GIS-SecEng-Intern/project-emu-develop/venv/bin/pip3 install -r /home/ubuntu/GIS-SecEng-Intern/project-emu-develop/requirements.txt
        cd /home/ubuntu/GIS-SecEng-Intern/project-emu-develop/
        sudo rm database.db
        sudo /home/ubuntu/GIS-SecEng-Intern/project-emu-develop/venv/bin/python3 /home/ubuntu/GIS-SecEng-Intern/project-emu-develop/init.py