FROM filigran/python-nodejs-fips:latest AS base

FROM base AS graphql-deps-builder

WORKDIR /opt/opencti-build/opencti-graphql
#cycode_ignore_violation_for_resource_here	
COPY opencti-graphql/package.json opencti-graphql/yarn.lock opencti-graphql/.yarnrc.yml ./
#cycode_ignore_violation_for_resource_here	
COPY opencti-graphql/.yarn ./.yarn
#cycode_ignore_violation_for_resource_here	
COPY opencti-graphql/patch ./patch
#cycode_ignore_violation_for_resource_here	
RUN set -ex; \
    apk add --no-cache git tini gcc g++ make musl-dev cargo postfix postfix-pcre gettext-dev \
    && npm install -g node-gyp \
    && yarn install --frozen-lockfile && yarn cache clean --all


FROM base AS graphql-builder

WORKDIR /opt/opencti-build/opencti-graphql
#cycode_ignore_violation_for_resource_here	
COPY opencti-graphql/package.json opencti-graphql/yarn.lock opencti-graphql/.yarnrc.yml ./
#cycode_ignore_violation_for_resource_here	
COPY opencti-graphql/.yarn ./.yarn
#cycode_ignore_violation_for_resource_here	
COPY opencti-graphql/patch ./patch
#cycode_ignore_violation_for_resource_here	
RUN set -ex; \
    apk add --no-cache git tini gcc g++ make musl-dev cargo postfix postfix-pcre gettext-dev \
    && npm install -g node-gyp \
    && yarn install
COPY opencti-graphql /opt/opencti-build/opencti-graphql
RUN yarn build:prod


FROM base AS front-builder

# Specify the versions of the APK packages
ENV GIT_VERSION=2.40.1-r0 \
    TINI_VERSION=0.19.0-r0 \
    GCC_VERSION=12.2.1_git20220924-r10 \
    GXX_VERSION=12.2.1_git20220924-r10 \
    MAKE_VERSION=4.3-r0 \
    MUSL_DEV_VERSION=1.2.3-r0 \
    CARGO_VERSION=1.66.1-r0 \
    POSTFIX_VERSION=3.8.0-r1 \
    POSTFIX_PCRE_VERSION=2.10-r1 \
    GETTEXT_DEV_VERSION=0.21.1-r1

WORKDIR /opt/opencti-build/opencti-front

COPY opencti-front/package.json opencti-front/yarn.lock opencti-front/.yarnrc.yml ./
COPY opencti-front/.yarn ./.yarn
COPY opencti-front/patch ./patch
COPY opencti-front/packages ./packages
RUN set -ex; \
    apk add --no-cache \
    git=$GIT_VERSION \
    tini=$TINI_VERSION \
    gcc=$GCC_VERSION \
    g++=$GXX_VERSION \
    make=$MAKE_VERSION \
    musl-dev=$MUSL_DEV_VERSION \
    cargo=$CARGO_VERSION \
    postfix=$POSTFIX_VERSION \
    postfix-pcre=$POSTFIX_PCRE_VERSION \
    gettext-dev=$GETTEXT_DEV_VERSION \
    && npm install -g node-gyp@8.2.0 \
    && yarn install

COPY opencti-front /opt/opencti-build/opencti-front
COPY opencti-graphql/config/schema/opencti.graphql /opt/opencti-build/opencti-graphql/config/schema/opencti.graphql

RUN yarn build:standalone


FROM base AS app

# Specify versions for pip, setuptools, and wheel
ENV PIP_VERSION=23.1.2 \
    SETUPTOOLS_VERSION=68.0.0 \
    WHEEL_VERSION=0.40.0

RUN set -ex; \
    apk add --no-cache git=2.40.1-r0 tini=0.19.0-r0 gcc=10.2.1_pre1-r3 g++=10.2.1_pre1-r3 make=4.3-r0 musl-dev=1.2.2-r1 cargo=1.47.0-r1 postfix=3.5.8-r0 postfix-pcre=2.10-r1 \
    && pip3 install --no-cache-dir --upgrade pip==$PIP_VERSION setuptools==$SETUPTOOLS_VERSION wheel==$WHEEL_VERSION

WORKDIR /opt/opencti

COPY opencti-graphql/src/python/requirements.txt ./src/python/requirements.txt

RUN pip3 install --no-cache-dir --requirement ./src/python/requirements.txt \
    && apk del git gcc musl-dev

COPY --from=graphql-deps-builder /opt/opencti-build/opencti-graphql/node_modules ./node_modules
COPY --from=graphql-builder /opt/opencti-build/opencti-graphql/build ./build
COPY --from=graphql-builder /opt/opencti-build/opencti-graphql/static ./static
COPY --from=front-builder /opt/opencti-build/opencti-front/builder/prod/build ./public
COPY opencti-graphql/src ./src
COPY opencti-graphql/config ./config
COPY opencti-graphql/script ./script

ARG UID=10000
ARG GID=10001
ARG USERNAME="_opencti"

ENV PYTHONUNBUFFERED=1
ENV NODE_OPTIONS="--force-fips --max_old_space_size=12288"
ENV NODE_ENV=production

RUN set -ex \
    ; addgroup -g "${GID}" -S "${USERNAME}" \
    && adduser \
        -h /opt/opencti \
        -g "OpenCTI privsep user" \
        -s "/sbin/nologin" \
        -G "${USERNAME}" \
        -S \
        -u "${UID}" \
        "${USERNAME}" \
    && install -o "${UID}" -g "${GID}" -m 0755 -d '/opt/opencti/logs' \
    && install -o "${UID}" -g "${GID}" -m 0755 -d '/opt/opencti/telemetry' \
    && install -o "${UID}" -g "${GID}" -m 0755 -d '/opt/opencti/.support'

VOLUME ["/opt/opencti/logs", "/opt/opencti/telemetry", "/opt/opencti/.support"]

USER "${USERNAME}"

ENTRYPOINT ["/sbin/tini", "--"]
CMD ["node", "build/back.js"]
