#!/usr/bin/env python3
"""
Extract mutation details from mutmut XML report and save as JSON.
Reads from mutation XMLs (generated by 'mutmut junitxml') to extract survived mutation details.
"""
import json
import sys
import os
import xml.etree.ElementTree as ET


def extract_from_xml(xml_file, output_file="mutation_details.json"):
    """Parse mutmut XML report for survived mutations with full details."""
    if not os.path.exists(xml_file):
        print(f"[MUTATION DETAILS] XML file not found: {xml_file}", file=sys.stderr)
        return None

    try:
        tree = ET.parse(xml_file)
        root = tree.getroot()
        survived = []

        testsuites = [root] if root.tag == 'testsuite' else root.findall('testsuite')

        for suite in testsuites:
            for testcase in suite.findall('testcase'):
                failure = testcase.find('failure')
                skipped = testcase.find('skipped')
                status = 'skipped' if skipped is not None else ('failure' if failure is not None else 'pass')

                if status == 'failure':
                    mutant_id = testcase.get('name', 'unknown')
                    failure_msg = failure.text or failure.get('message', '')

                    survived.append({
                        "id": mutant_id,
                        "line": testcase.get('line', 'unknown'),
                        "status": status,
                        "message": failure_msg.strip() if failure_msg else "No details",
                        "description": f"**{mutant_id}** — {failure_msg[:200]}" if failure_msg else f"**{mutant_id}** — No details"
                    })

        output = {
            "survived_count": len(survived),
            "mutations": survived
        }

        with open(output_file, "w", encoding='utf-8') as f:
            json.dump(output, f, indent=2, ensure_ascii=False)

        print(f"[MUTATION DETAILS] Extracted {len(survived)} mutation details to {output_file}")
        return output_file

    except ET.ParseError as e:
        print(f"[MUTATION DETAILS] XML parse error: {e}", file=sys.stderr)
        return None
    except UnicodeDecodeError as e:
        print(f"[MUTATION DETAILS] Encoding error reading XML: {e}", file=sys.stderr)
        return None
    except Exception as e:
        print(f"[MUTATION DETAILS] Error extracting: {e}", file=sys.stderr)
        return None


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 extract_mutation_details.py <xml_file> [output_json_file]", file=sys.stderr)
        sys.exit(1)

    xml_file = sys.argv[1]
    output_file = sys.argv[2] if len(sys.argv) > 2 else "mutation_details.json"
    extract_from_xml(xml_file, output_file)
