---
# this specifies which servers to run this on
- hosts: all
  gather_facts: false
# means to become sudo
  become: true
  become_user: root
  become_method: sudo
  vars:
    created_username: ns-quinlan

  tasks:
    - name: Update apt
      apt:
        update_cache: yes
        upgrade: 'yes'  
    - name: Update apt and install required system packages
      apt:
        pkg:
          - curl
          - vim
          - git
        state: latest
        update_cache: true
    - name: Install nginx
      apt:
        name: nginx
        state: latest
    - name: Configuring Ubuntu user
      expect:
        command: sudo passwd ubuntu
        responses:
          "New password:": "ubuntu"
          "Retype new password:": "ubuntu"
        timeout: 200
    - name: Installing Dependencies
      shell: |
        sudo apt-get install python3-pip python3-dev build-essential libssl-dev libffi-dev python3-setuptools -y
        sudo apt-get install python3-venv -y
        sudo apt-get update
    - name: Cloning GitHub Repository
      command: sudo rm -r /home/ubuntu/GIS-SecEng-Intern && git clone https://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@github.com/netSkope/GIS-SecEng-Intern.git --single-branch --branch FLASK_webserver
      args:
        chdir: /home/ubuntu/
        creates: /GIS-SecEng-Intern/
      ignore_errors: true
    - name: Python Virtual Environment
      shell: |
        sudo python3 -m venv /home/ubuntu/GIS-SecEng-Intern/flask_app/venv
        sudo /home/ubuntu/GIS-SecEng-Intern/flask_app/venv/bin/pip3 install --upgrade pip
        sudo /home/ubuntu/GIS-SecEng-Intern/flask_app/venv/bin/pip3 install wheel gunicorn Flask
    - name: Configuring GUnicorn
      shell: |
        sudo cp /home/ubuntu/GIS-SecEng-Intern/Ansible/files/myproject.service /etc/systemd/system/
        sudo chown ubuntu:ubuntu /home/ubuntu/GIS-SecEng-Intern/
        sudo systemctl start myproject
    - name: Starting GUnicorn
      expect:
        command: systemctl daemon-reload
        responses:
          "Password:": "ubuntu"
        timeout: 200
    - name: Enable GUnicorn
      shell: |
        sudo systemctl enable myproject
        sudo systemctl status myproject
    - name: Configuring Nginx to Proxy Requests
      shell: |
        sudo cp /home/ubuntu/GIS-SecEng-Intern/Ansible/files/myproject /etc/nginx/sites-available/
        sudo ln -s /etc/nginx/sites-available/myproject /etc/nginx/sites-enabled
        sudo nginx -t
        sudo systemctl restart nginx
        sudo ufw delete allow 5000
        sudo ufw allow 'Nginx Full'
        sudo chmod 755 /home/ubuntu
