---
# this specifies which servers to run this on
- hosts: all
  gather_facts: false
# means to become sudo
  become: true
  become_user: root
  become_method: sudo
  vars:
    created_username: ns-quinlan

  tasks:
    - name: Update apt
      apt:
        update_cache: yes
        upgrade: 'yes'  
    - name: Update apt and install required system packages
      apt:
        pkg:
          - curl
          - vim
          - git
        state: latest
        update_cache: true
    - name: Install nginx
      apt:
        name: nginx
        state: latest
    - name: Configuring Ubuntu user
      expect:
        command: sudo passwd ubuntu
        responses:
          "New password:": "ubuntu"
          "Retype new password:": "ubuntu"
        timeout: 200
    - name: Installing Dependencies
      shell: |
        sudo apt-get install python3-pip python3-dev build-essential libssl-dev libffi-dev python3-setuptools -y
        sudo apt-get install python3-venv -y
        sudo apt-get update
    - name: Cloning GitHub Repository
      shell: sudo rm -r /home/ubuntu/GIS-SecEng-Intern && git clone https://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@github.com/netSkope/GIS-SecEng-Intern.git --single-branch --branch FLASK_webserver
    - name: Python Virtual Environment
      shell: |
        sudo python3 -m venv /home/ubuntu/GIS-SecEng-Intern/flask_app/venv
        sudo /home/ubuntu/GIS-SecEng-Intern/flask_app/venv/bin/pip3 install --upgrade pip
        sudo /home/ubuntu/GIS-SecEng-Intern/flask_app/venv/bin/pip3 install wheel gunicorn Flask
    - name: Configuring GUnicorn
      shell: |
        sudo cp /home/ubuntu/GIS-SecEng-Intern/Ansible/files/myproject.service /etc/systemd/system/
        sudo chown ubuntu:ubuntu /home/ubuntu/GIS-SecEng-Intern/flask_app/
    - name: Restarting Systemd Service
      shell: sudo systemctl daemon-reload && sudo systemctl restart myproject
    - name: Enable GUnicorn
      shell: |
        sudo systemctl start myproject
        sudo systemctl enable myproject
        sudo systemctl status myproject
    - name: Configuring Nginx to Proxy Requests
      shell: |
        sudo cp /home/ubuntu/GIS-SecEng-Intern/Ansible/files/myproject /etc/nginx/sites-available/
        sudo ln -s /etc/nginx/sites-available/myproject /etc/nginx/sites-enabled
        sudo nginx -t
        sudo systemctl restart nginx
        sudo ufw delete allow 5000
        sudo ufw allow 'Nginx Full'
        sudo chmod 755 /home/ubuntu
    # Generate Certificate Authority (CA) self-signed certificate
    - name: Generate Certificate Authority (CA) self-signed certificate
      block:
        - name: Generate Root CA private key
          openssl_privatekey:
            path: /etc/ssl/private/nginx-selfsigned.key

        - name: Generate Root CA CSR
          openssl_csr:
            path: "/etc/ssl/certs/nginx-selfsigned.csr"
            privatekey_path: "/etc/ssl/private/nginx-selfsigned.key"
            common_name: 13.52.105.27
            organization_name: Netskope
            organizational_unit_name: Security Engineering
            basic_constraints:
              - CA:TRUE
            basic_constraints_critical: yes
            key_usage:
              - keyCertSign
              - digitalSignature
              - cRLSign
            key_usage_critical: yes

        - name: Generate Root CA certificate
          openssl_certificate:
            path: "/etc/ssl/certs/nginx-selfsigned.crt"
            privatekey_path: "/etc/ssl/private/nginx-selfsigned.key"
            csr_path: "/etc/ssl/certs/nginx-selfsigned.csr"
            provider: selfsigned
    # /Generate Certificate Authority (CA) self-signed certificate
    - name: Securing the Application
      shell: |
        sudo cp /home/ubuntu/GIS-SecEng-Intern/Ansible/files/self-signed.conf /etc/nginx/snippets/
        sudo cp /home/ubuntu/GIS-SecEng-Intern/Ansible/files/ssl-params.conf /etc/nginx/snippets/
        sudo openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048
        sudo ln -s /etc/nginx/sites-available/myproject /etc/nginx/sites-enabled
        sudo ufw app list
        sudo systemctl restart nginx
    - name: Implementing Fail2Ban
      shell: |
        sudo rm -r /home/ubuntu/fail2ban && git clone https://github.com/fail2ban/fail2ban.git
        cd fail2ban
        sudo python3 setup.py install 
    - name: Updating Fail2Ban Conf Files
      shell: |
        sudo cp /home/ubuntu/GIS-SecEng-Intern/Ansible/fail2ban/fail2ban.conf && /etc/fail2ban/
        sudo cp /home/ubuntu/GIS-SecEng-Intern/Ansible/fail2ban/paths-arch.conf && /etc/fail2ban/
        sudo cp /home/ubuntu/GIS-SecEng-Intern/Ansible/fail2ban/paths-common.conf && /etc/fail2ban/
        sudo cp /home/ubuntu/GIS-SecEng-Intern/Ansible/fail2ban/paths-debian.conf && /etc/fail2ban/
        sudo cp /home/ubuntu/GIS-SecEng-Intern/Ansible/fail2ban/paths-fedora.conf && /etc/fail2ban/
        sudo cp /home/ubuntu/GIS-SecEng-Intern/Ansible/fail2ban/paths-freebsd.conf && /etc/fail2ban/
        sudo cp /home/ubuntu/GIS-SecEng-Intern/Ansible/fail2ban/paths-openuse.conf && /etc/fail2ban/
        sudo cp /home/ubuntu/GIS-SecEng-Intern/Ansible/fail2ban/paths-osx.confs && /etc/fail2ban/
    # To enable fail2ban as an automatic service, simply copy the script for your distro from the files directory to /etc/init.d. 
    # Example (on a Debian-based system):
    - name: Fail2Ban Configuration
      expect:
        command: |
          cd fail2ban
          sudo cp files/debian-initd /etc/init.d/fail2ban
          update-rc.d fail2ban defaults
          sudo service fail2ban start
        responses:
          "Password:": "ubuntu"
        timeout: 200
