---
# this specifies which servers to run this on
- hosts: all
  gather_facts: false
# means to become sudo
  become: true
  become_user: root
  become_method: sudo
  vars:
    created_username: ns-quinlan

  tasks:
    - name: Update apt
      apt:
        update_cache: yes
        upgrade: 'yes'
    - name: Install OpenJDK 11 with APT
      command: sudo apt-get -y install openjdk-11-jdk
    - name: Make OpenJDK 11 the default
      command: sudo update-java-alternatives -s java-1.11.0-openjdk-amd64
    # another way of saying sudo apt install nginx
    - name: Install nginx
      apt:
        name: nginx
        state: latest
    - name: Install pip
      apt:
        update_cache: yes
        name: python3-pip
    - name: Setup passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'
    - name: Create a new regular user with sudo privileges
      user:
        name: "{{created_username}}"
        state: present
        groups: sudo 
        append: true
        create_home: true
    - name: Disable password auth for root
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin prohibit-password'
    - name: Update apt and install required system packages
      apt:
        pkg:
          - curl
          - vim
          - git
          - ufw
        state: latest
        update_cache: true
    - name: UFW - Allow SSH connections
      community.general.ufw:
        rule: allow
        name: OpenSSH
    - name: UFW - Enable and deny by default
      community.general.ufw:
        state: enabled
        default: deny
    - name: Copy Cobalt Strike
      copy:
        src: ./files/cobaltstrike-dist.tgz
        dest: /tmp/cobaltstrike-dist.tgz
    - name: Extract Cobalt Strike
      command: sudo tar -xvzf /tmp/cobaltstrike-dist.tgz -C /tmp/
    - name: Update Cobalt Strike
      ignore_errors: yes
      expect:
        command: timeout 900 ./update
        chdir: "/tmp/cobaltstrike/"
        responses:
          "Please enter your license key:": "{{license_key}}"
        timeout: 200
  
    - name: Create and set JAVA_OPTS in custom file
      blockinfile:
        path: /home/ubuntu/my_environment
        block: |
          export JAVA_OPTS="$JAVA_OPTS -Dhttps.protocols=TLSv1.2 -Djdk.tls.client.protocols=TLSv1.2 -Djava.security.egd=file:/dev/./urandom"
        create: yes
    - name: Reload /home/ubuntu/my_environment
      shell: . /home/ubuntu/my_environment

    - name: Starting Cobalt Strike Team Server
      shell: nohup sudo ./teamserver 10.0.1.50 password &
      args:
        chdir: "/tmp/cobaltstrike/"