---
- hosts: all
  become: true
  become_user: root
  become_method: sudo
  vars:
    created_username: ns-quinlan

  tasks:
    - name: Another way to call known_hosts
      ansible.builtin.known_hosts:
        name: 54.183.103.225   # or 10.9.8.77
        key: 54.183.103.225,54.183.103.225 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDE59BkYUjpDfZJDnVTO2o24h7bX5wtUTVD0rgLEG/vyPywXyybiY8EqDHxPirs6NSplyDLjTPav76i514yWsI20uKOLvlekwFixtGsUNi8KLdgck/oe+O54RZ1HVdjRvgHWHECo8rIRBJLAdxUs7vOtAC1hH7OXlfhAXeSWRlxUz8LwJt9ECnMhn7mj1L2s+fucQh/kpruq9D/Zd7u2grKYApN5XKPAtut7CmypVwcJA2C1bdRbGNqIk5uY6DnY2yD0TIYdy5jj+5lcNRXU8JyISSjvL9H0qDzJhTVjDrdq+aQ6OVxYbCL08zV06YYF1zvZ3g+wSirh5b5xy0NIQn9qIFNGJnQI8z6ei4m1GemgZR8TaORlZhGN1DdT1XY81o0md5ipwxky5B8mKH0I7+BxQO/oxxiSwxAEhhJuWQdF2leOR14VvbSPZ+lcHSvPDw5GQtgJU0XPTESjaglmLgqQH4XqQ1qxlfF4Gb/l+lpFAXePFGCXMYyYMDM7IQUbcs=
        path: /.ssh/known_hosts
        state: present
    - name: Install nginx
      apt:
        name: nginx
        state: latest
    - name: Install pip
      apt:
        update_cache: yes
        name: python3-pip
    - name: Setup passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'
    - name: Create a new regular user with sudo privileges
      user:
        name: "{{created_username}}"
        state: present
        groups: sudo 
        append: true
        create_home: true
    - name: Disable password auth for root
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin prohibit-password'
    - name: Update apt and install required system packages
      apt:
        pkg:
          - curl
          - vim
          - git
          - ufw
        state: latest
        update_cache: true
    - name: UFW - Allow SSH connections
      community.general.ufw:
        rule: allow
        name: OpenSSH
    - name: UFW - Enable and deny by default
      community.general.ufw:
        state: enabled
        default: deny
    - name: Copy Cobalt Strike
      copy:
        src: cobaltstrike-dist.tgz
        dest: /tmp/cobaltstrike-dist.tgz
    - name: Install Cobalt Strike
      apt:
        deb: /tmp/cobaltstrike-dist.tgz
      become: true
