name: Cleanup Failed Workflows

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete failed workflows older than a week
        env:
          NSCQUINLAN_GHA_TOKEN: ${{ secrets.NSCQUINLAN_GHA_TOKEN}}
        run: |
          echo "Fetching failed workflow runs older than two weeks..."
          two_weeks_ago=$(date -d '14 days ago' --utc +%Y-%m-%dT%H:%M:%SZ)
          repo="netSkope/GIS-SecEng-Intern"
          response=$(curl -s -H "Authorization: token $NSCQUINLAN_GHA_TOKEN" "https://api.github.com/repos/$repo/actions/runs?status=failure&per_page=100")
          
          echo "API response: $response"
          
          failed_runs=$(echo "$response" | jq -r --arg two_weeks_ago "$two_weeks_ago" '.workflow_runs[] | select(.created_at < $two_weeks_ago) | .id')
          
          if [ -z "$failed_runs" ]; then
            echo "No failed workflow runs found older than two weeks."
          else
            for run_id in $failed_runs; do
              echo "Deleting workflow run $run_id..."
              curl -s -X DELETE -H "Authorization: token $NSCQUINLAN_GHA_TOKEN" "https://api.github.com/repos/$repo/actions/runs/$run_id"
            done
            echo "Cleanup complete!"
          fi