
name: Upload to GCS

on:
  push:
    branches:
      - ns-tsingh

jobs:
  upload-to-gcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Install Vault CLI
      #   run: |
      #              curl -LO https://releases.hashicorp.com/vault/1.15.0/vault_1.15.0_linux_amd64.zip
      #              unzip vault_1.15.0_linux_amd64.zip
      #              sudo mv vault /usr/local/bin/
        
                   
            
      # - name: Authenticate to Vault
      #   env:
      #       VAULT_APPROLE_IDA: ${{ secrets.GH_ACTIONS_VAULT_APPROLE_ID }}      
      #       VAULT_SECRET_IDA: ${{ secrets.GH_ACTIONS_APPROLE_SECRET }}
      #   run: |      
      #         vault --version
      #         export VAULT_ADDR="https://global.prod.kms.nskope.net"  
      #         export VAULT_NAMESPACE="gis"
      #         export VAULT_ROLE_ID="$VAULT_APPROLE_IDA"        
      #         export VAULT_SECRET_ID="$VAULT_SECRET_IDA"
      #         export VAULT_TOKEN=$(vault write -field=token auth/approle/login role_id="$VAULT_ROLE_ID" secret_id="$VAULT_SECRET_ID")    

  
      - name: fetch key from hashicorp vault
        run : |
              export SECRET_KEY=$(vault kv get -field=serviceAccountJSONKey github-action/siem-231719-json-creds)
                

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{secrets.GCP_SIEM_SERVICEACCOUNT_JSONKEY}}'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-cloud-storage
      
      

      - name: Run Python script to upload file to GCS
        run: |  
           python dump_csv.py 

      - name: List contents of the GCS bucket
        run: |
         gcloud storage ls gs://test-saas-bucket

      - name: info about the object 
        run: |
           gcloud storage objects describe gs://test-saas-bucket/test.csv
    
     