# For more informatio on how to setup GitHub Actions with Terraform, documentation is here:
# https://developer.hashicorp.com/terraform/tutorials/automation/github-actions
# https://www.pluralsight.com/resources/blog/cloud/how-to-use-github-actions-to-automate-terraform

name: Flask Web Server

on:
  push:
    branches: [ "FLASK_webserver" ]
  pull_request:
    branches: [ "FLASK_webserver" ]

jobs:
  flaskapp:
    if: github.repository != 'netSkope/GIS-SecEng-Intern/FLASK_webserver'
    name: "Flask Prod Web Server"
    runs-on: ["self-hosted", "linux", "x64", "sz-XS", "gh", "cheap"]
    permissions:
      contents: read
      pull-requests: write
    steps:
    # Checkout checks out the repository. Uses defines the GitHub action or Docker image to run that specific step. 
    # The checkout step uses GitHub's actions/checkout@v3 action.
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    # Responsible for running Commands on Runner
    - name: Configuring Runner...
      id: runner
      run: |
          sudo apt install python3-pip
          sudo apt install sshpass
          pip install ansible
          sudo apt update
    # Responsible for setting up SSH on Self-Hosted Server to connect with Ubuntu Server 
    - name: Set Up SSH Host key
      run: |
        mkdir -p ~/.ssh/
        echo -e "-----BEGIN RSA PRIVATE KEY-----\n${{secrets.SECENG_INTERN_KEY_PAIR}}\n-----END RSA PRIVATE KEY-----" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa ${{ env.TF_IP_ADDRESS }} >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
    # Running commands to SSH into Ubuntu Server from Self-Hosted Server with Ansible
    - name: Running Ansible Playbook...
      id: playbook
      working-directory: ./Ansible
      run: |
          echo -e 54.151.54.243 >> ./inventory/hosts
          ansible-playbook -vvv ./playbooks/playbook.yml -u ubuntu -i ./inventory/hosts -e "ip_address=54.151.54.243"