name: Run Hello World

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch: # Correctly standalone to enable the manual run button

jobs:
  execute-python:
    runs-on: [self-hosted, linux, x64, rg-default, sz-XS, gh, cheap]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run Hello World Script
        run: python helloworld.py
