name: Test Password Strength App

on:
  push:
    branches: [ "ns-shristy" ] # Tells GitHub: "Only run this when shristy pushes code!"

jobs:
  test-frontend:
    runs-on: arc-default-basic-cheap-s-set # Your special self-hosted runner!

    steps:
      - name: Get copy of my code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Streamlit
        working-directory: ./NIC-SecEng-Task/Password-Checker
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Automated Python Tests
        working-directory: ./NIC-SecEng-Task/Password-Checker
        run: python test_password.py