# name: SSL Script
# on:
#   push:
#     branches: [ "AppSec" ]
#   pull_request:
#     branches: [ "AppSec" ]
#   workflow_dispatch:
#   schedule:
#     - cron: '1 1 * * 2'


# jobs:
#   build:

#     runs-on: ["self-hosted", "linux", "x64", "sz-XS", "gh", "cheap"]

#     steps:
#     - uses: actions/checkout@v4.0.0
#     - name: Set up Python 3.8 - 10 
#       uses: actions/setup-python@v4.0.0
#       with:
#         python-version: 3.8
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
