name: SSH ACTION

on:
  push:
    branches: [ "ns-cquinlan" ]
  pull_request:
    branches: [ "ns-cquinlan" ]

jobs:
  deploy:
    runs-on: ["self-hosted", "linux", "x64", "sz-XS", "gh", "cheap"]
    steps:
      - uses: actions/checkout@v4
      - name: Install SSH Key
        working-directory: ./Ansible
      - run: |
          cp 
          ssh -i seceng-intern-key-pair.pem ubuntu@54.183.103.225
          ls
          touch lmao.txt