name: Terraform Plan Action

on:
  push:
    branches: [ "ns-cquinlan" ]
  pull_request:
    branches: [ "ns-cquinlan" ]

jobs:
  deploy:
    runs-on: ["self-hosted", "linux", "x64", "sz-XS", "gh", "cheap"]
    steps:
      - name: Install SSH Key
        uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
        with:
          ORIGIN: 54.183.103.225 # example.com || 8.8.8.8
          SSHKEY: ${{ secrets.SECENG_INTERN_KEY_PAIR }} # ----- BEGIN RSA PRIVATE KEY----- ...
          NAME: production
          PORT: 22 # 3000
          USER: ubuntu # admin