name: SSH ACTION

on:
  push:
    branches: [ "ns-cquinlan" ]
  pull_request:
    branches: [ "ns-cquinlan" ]

jobs:
  deploy:
    runs-on: ["self-hosted", "linux", "x64", "sz-XS", "gh", "cheap"]
    
    steps:

      - uses: actions/checkout@v4
    
      - name: Install SSH Key
        id: ssh
        working-directory: ./Ansible
        env:
          ssh-private-key: ${{ secrets.SECENG_INTERN_KEY_PAIR_CQUINLAN }}
        run: |
          echo -e "-----BEGIN RSA PRIVATE KEY-----\n$(cat ${{ secrets.SECENG_INTERN_KEY_PAIR_CQUINLAN }})\n-----END RSA PRIVATE KEY-----" > key-file.pem
          chmod 600 key-file.pem
          ssh ubuntu@54.183.103.225 -tt -i key-file.pem
          echo "Success!"