name: Terraform GH Action

on:
  push:
    branches: [ "ns-cquinlan" ]
  pull_request:
    branches: [ "ns-cquinlan" ]

jobs:
  build:

    runs-on: ["self-hosted", "linux", "x64", "sz-XS", "gh", "cheap"]

    steps:
    - uses: actions/checkout@v3
    - name: Install Terraform packages
      run: |
        terraform init
        terraform plan
#        terraform apply
#        python -m pip install flake8 pytest
#        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi