# For more informatio on how to setup GitHub Actions with Terraform, documentation is here:
# https://developer.hashicorp.com/terraform/tutorials/automation/github-actions
# https://www.pluralsight.com/resources/blog/cloud/how-to-use-github-actions-to-automate-terraform

name: Terraform Plan Action

on:
  push:
    branches: [ "ns-cquinlan" ]
  pull_request:
    branches: [ "ns-cquinlan" ]

jobs:
  terraform:
    if: github.repository != 'netSkope/GIS-SecEng-Intern/ns-cquinlan'
    name: "Terraform Plan"
    runs-on: ["self-hosted", "linux", "x64", "sz-XS", "gh", "cheap"]
    permissions:
      contents: read
      pull-requests: write
    steps:

    # Checkout checks out the repository. Uses defines the GitHub action or Docker image to run that specific step. 
    # The checkout step uses GitHub's actions/checkout@v3 action.
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v2
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false
    # - name: Import Secrets
    #   id: import-secrets
    #   uses: hashicorp/vault-action@v2
    #   with:
    #     url: "https://www.google.com"
    #     token: ${{secrets.VAULT_TOKEN}}
    #     caCertificiate: ${{secrets.VAULT_CA_CERT}}
    #     roleId: ${{secrets.VAULT_ROLE_ID}}
    #     secretId: ${{secrets.VAULT_SECRET_ID}}
    #     secrets: |
    #         secret/data/ci/aws accessKey | secrets.AWS_ACCESS_KEY ;
    #         secret/data/ci/aws secretKey | secrets.AWS_SECRET_ACCESS_KEY ;
    #         secret/data/ci npm_token
        # secret/data/ci/aws * will specify a wildcard for the key name to get all keys in the path.
    - name: Downloading necessary Terraform AWS Ec2 Packages...
      id: init
      working-directory: ./Terraform
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      run: terraform init 
    # THIS CAN BE UNCOMMENTED WHEN AWS SERVER IS RUNNING
    - name: Planning AWS Ec2 Server...
      id: plan
      working-directory: ./Terraform
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      run: terraform plan -no-color
    # THIS CAN BE UNCOMMENTED WHEN AWS SERVER IS RUNNING
    - name: Applying AWS Ec2 Server...
      id: apply
      working-directory: ./Terraform
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      run: terraform apply -auto-approve | 
        echo TF_IP_ADDRESS=$(terraform output -raw server_public_ip) >> $GITHUB_ENV
    - name: Grabbing Public IP
      id: publicip
      run: echo ${{ env.TF_IP_ADDRESS }}
    # THIS CAN BE UNCOMMENTED WHEN AWS SERVER IS RUNNING
    # - name: Destroying AWS Ec2 Server...
    #   id: destroy
    #   run: terraform destroy -no-color
    #   | yes
    #   continue-on-error: true
    - name: Running Ansible Commands...
      id: Ansible
      run: 
          sudo apt install python3-pip
          pisp install ansible
          ansible-playbook playbook.yml -i {{ env.TF_IP_ADDRESS }} -u ubuntu -k
        
