name: Upload Python Code

on:
  workflow_dispatch:
permissions:
  contents: write
  
jobs:
  create-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create code.py
        run: |
          echo "print('Hello, World!')" > code.py

      - name: Commit & Push File
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add code.py
          git commit -m "Add code.py using GitHub Actions"
          git push